#!/bin/sh ruby

require 'fileutils'
require 'mini_magick'
IMAGEOPTIM_BIN_PATH='node_modules/.bin/imageoptim'

image_list_from_git = `git diff --name-only --cached -- source/images`.lines.map(&:chomp)
images = image_list_from_git.select { |filepath| File.exists? filepath }.select { |filepath| File.extname(filepath) == '.png' }
if images.any?
  images.each do |image_path|
    mini_magick_image = MiniMagick::Image.new image_path
    # FIXME: Execute this only when the size NEEDS to be changed. Otherwise this creates a new file
    # which seems to trigger imageoptim again, which seems to update the image and we are in a loop.
    if mini_magick_image.width > 700
      puts "Resizing image: #{image_path} which is too wide: #{mini_magick_image.width} > 700"
      mini_magick_image.resize('700x1000>')
    end
    system "echo '#{image_path}' | #{IMAGEOPTIM_BIN_PATH}"
    system "git add '#{image_path}'"
  end
else
  puts "Skipping imageoption since there are no modified or new images to be commited"
end

